kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: sivakumar
  annotations:
    kubernetes.io/created-by: 'prudvi'
    jenkins-url: 'http://jenkins.daws-78s.site:8080/'
spec:
  containers:
  - name: nginx
    image: nginx