apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: pod-1
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
---


apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-1
    purpose: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
          - key: purpose
            operator: In
            values:
            - affinity
        topologyKey: topology.kubernetes.io/zone
    
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:2.0

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    name: pod-1
    purpose: affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
          - key: purpose
            operator: In
            values:
            - affinity
        topologyKey: "kubernetes.io/hostname"
    
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:2.0