apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: fs-0e6292c11dc276f59